baseURL = 'https://wasiful.netlify.app/'
languageCode = 'en-us'
title = 'Wasif - Portfolio'
theme = 'PaperMod'

[params]
  author = "Wasif"
  description = "Portfolio of Wasif – IT Field Engineer, Data Analyst, and Researcher"
  keywords = ["Portfolio", "Data Analysis", "Research", "IT Engineer"]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  defaultTheme = "auto"
  DateFormat = "January 2, 2006"

  email = "wasiful2016@gmail.com"
  phone = "+420776895697"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:wasiful2016@gmail.com"
    title = "wasiful2016@gmail.com"

  [[params.socialIcons]]
    name = "phone"
    url = "tel:+420776895697"
    title = "+420776895697"

[params.profileMode]
  enabled = true
  title = "Wasif"
  subtitle = "IT Infrastructure Engineer • Scientific Data Analysis • Researcher in Physics"
  imageUrl = "profile.jpg"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Wasif"

  [[params.profileMode.buttons]]
    name = "About Me"
    url = "/about/"

  [[params.profileMode.buttons]]
    name = "Projects"
    url = "/projects/"

  [[params.profileMode.buttons]]
    name = "Publications"
    url = "/publications/"

  [[params.profileMode.buttons]]
    name = "Contact"
    url = "/contact/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4
